### ISSUE TITLE
loader.py fails with Python 2.7

### ISSUE THREAD

**Issue by scruplelesswizard** [stfc/ceph-InfluxDB-metricsCollector#2]
Running _loader.py_ with Python 2.7.6 I receive the following error for each plugin run:

```
[2016-06-19 22:13:55,211] ERROR: Failed to execute command :: stdout argument not allowed, it will be overridden. :: Traceback (most recent call last):
  File "/opt/collins/ceph-InfluxDB-metricsCollector/plugins/base.py", line 114, in execute_command
    output = subprocess.check_output(args,stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 565, in check_output
    raise ValueError('stdout argument not allowed, it will be overridden.')
ValueError: stdout argument not allowed, it will be overridden.
```

Per [Pyton 2.7  subprocess docs](https://docs.python.org/2/library/subprocess.html#subprocess.check_output) the arguments for `subprocess.check_output` do not include `stdout`, but [the base.py call](https://github.com/stfc/ceph-InfluxDB-metricsCollector/blob/master/plugins/base.py#L114) does include the `stdout` argument.

Is this a localized issue, or is this something that should be fixed in the codebase?

**Comment by ITDebicki** [comment]
It was a codebase issue, due to me not reading the check_output docs properly and removing stdin rather than stdout. Thank you for bringing it up.
